-- SCRIPT DE BASE DE DATOS PARA PROYECTO DE SOPORTE (PANEL-SOPORTE)
-- Copia y pega este script en el SQL Editor de tu Dashboard de Supabase.

-- 1. TABLA DE PERFILES (Extensión de Auth.users)
-- Guarda información adicional de los usuarios y su rol.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT NOT NULL,
  role TEXT DEFAULT 'cliente' CHECK (role IN ('cliente', 'administrador')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS en profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para profiles
CREATE POLICY "Los usuarios pueden ver su propio perfil" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Los administradores pueden ver todos los perfiles" 
  ON public.profiles FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'administrador'
    )
  );

-- 2. TABLA DE TICKETS
-- Para el sistema de soporte técnico.
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT DEFAULT 'Media' CHECK (priority IN ('Baja', 'Media', 'Alta')),
  status TEXT DEFAULT 'Abierto' CHECK (status IN ('Abierto', 'En Proceso', 'Resuelto', 'Cerrado')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS en tickets
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para tickets
CREATE POLICY "Clientes pueden ver sus propios tickets" 
  ON public.tickets FOR SELECT 
  USING (auth.uid() = client_id);

CREATE POLICY "Clientes pueden crear sus propios tickets" 
  ON public.tickets FOR INSERT 
  WITH CHECK (auth.uid() = client_id);

CREATE POLICY "Administradores pueden ver todos los tickets" 
  ON public.tickets FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'administrador'
    )
  );

CREATE POLICY "Administradores pueden actualizar cualquier ticket" 
  ON public.tickets FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'administrador'
    )
  );

-- 3. TABLA DE CITAS (APPOINTMENTS)
-- Para programar visitas o llamadas.
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  appointment_date TIMESTAMPTZ NOT NULL,
  notes TEXT,
  status TEXT DEFAULT 'Solicitada' CHECK (status IN ('Solicitada', 'Confirmada', 'Cancelada', 'Reprogramar')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS en appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para appointments
CREATE POLICY "Clientes pueden ver sus propias citas" 
  ON public.appointments FOR SELECT 
  USING (auth.uid() = client_id);

CREATE POLICY "Clientes pueden solicitar sus propias citas" 
  ON public.appointments FOR INSERT 
  WITH CHECK (auth.uid() = client_id);

CREATE POLICY "Administradores pueden ver todas las citas" 
  ON public.appointments FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'administrador'
    )
  );

CREATE POLICY "Administradores pueden actualizar cualquier cita" 
  ON public.appointments FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'administrador'
    )
  );

-- 4. TRIGGER PARA CREAR PERFIL AUTOMÁTICAMENTE
-- Crea una fila en public.profiles cada vez que un usuario se registra en Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name', 'cliente');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Eliminamos el trigger si existe para recrearlo
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. REPARACIÓN PARA USUARIOS EXISTENTES
-- Si ya tenías usuarios creados ANTES de correr este script, sus perfiles no existen.
-- Ejecuta esto para crear los perfiles que falten:
INSERT INTO public.profiles (id, email, role)
SELECT id, email, 'cliente'
FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;

-- NOTA: Para hacer a un usuario ADMINISTRADOR, ejecuta esto manualmente en el SQL Editor:
-- UPDATE public.profiles SET role = 'administrador' WHERE email = 'tu-email@ejemplo.com';
